[project]
name = "new-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "flask-cors>=6.0.2",
    "g2p-en>=2.1.0",
    "gunicorn>=25.1.0",
    "levenshtein>=0.27.3",
    "psycopg2-binary>=2.9.11",
    "pystemmer>=3.0.0",
    "sqlalchemy>=2.0.0",
    "num2words",
    "nltk",
    "Levenshtein",
    "tqdm",
    "python-dotenv>=1.2.2",
]
